# Generated by Django 4.2.3 on 2023-08-12 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('task_start_time', models.TimeField(default=datetime.datetime.now)),
                ('task_end_time', models.TimeField(default=datetime.datetime(2023, 8, 12, 22, 8, 37, 420270))),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Todo',
            },
        ),
    ]
