# Generated by Django 4.2.3 on 2023-08-12 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='task_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 12, 22, 26, 47, 344539)),
        ),
    ]
